### PR TITLE
S3storage

### PR DESCRIPTION
**Pull request by gouthambs**
@Speedy1991 
Adds functionality mentioned in #8 .

Let me test this out during this week and will ping you.

### CODE REVIEW

**Comment by Speedy1991** [comment]
hm, there are many code duplications compared to the normal Storage. Maybe a abstract Storage would be better. I'll think about it.

**Comment by Speedy1991** [comment]
What do you think about something like [this](https://github.com/Speedy1991/Flask-FileUpload/blob/feature/abstract_storage/flask_fileupload/storage.py)?

**Comment by gouthambs** [comment]
This looks good. I can update to your new specification.

**Comment by Speedy1991** [comment]
#10 done

**Pull request closed without merging**
